version: '3.8'
services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
      MYSQL_USER: root
    ports:
      - "3306:3306"

  php-apache-environment:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'laravel-app'
    volumes:
      - . /var/www/html/
    ports:
      - "8080:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    depends_on:
      - db
      - php-apache-environment
