apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: laravel-app
spec:
  selector:
      matchLabels:
        app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              value: root
          image: phpmyadmin/phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
