apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: laravel-app
spec:
  selector:
    name: phpmyadmin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 80


