apiVersion: v1
kind: Service
metadata:
  name: laravel-app-db
  namespace: laravel-app
spec:
  selector:
    app: laravel-app-db
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3306 
    targetPort: 3306 