apiVersion: v1
kind: Service
metadata:
  name: laravel-app-php-apache
  namespace: laravel-app
spec:
  selector:
    app: laravel-app-php-apache
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000 
    targetPort: 5000 