apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: php-apache-environment
  name: php-apache-environment
  namespace: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php-apache-environment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: php-apache-environment
    spec:
      containers:
        - image: triple3a/laravel-app
          name: php-apache-environment
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: . /var/www/html/
              name: php-apache-environment-claim0
      restartPolicy: Always
      volumes:
        - name: php-apache-environment-claim0
          persistentVolumeClaim:
            claimName: php-apache-environment-claim0
status: {}
