apiVersion: v1
kind: Service
metadata:
  name: laravel-app-phpmyadmin
  namespace: laravel-app
spec:
  selector:
    app: laravel-app-phpmyadmin
# ClusterIP (default), LoadBalancer (works on cloud), NodePort (most used)
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4000 
    targetPort: 4000 